Update PlayFab.Build.cs
Fixed compile error PlayFab.Build.cs(19,16): error CS1520: Yöntemin bir dönüş türü olmalıdır " (The method need to have a return value)